development:
  adapter: postgresql
  host: localhost
  database: development_employees_manager
  pool: 5
  username: postgres
  password:
  encoding: utf8

test: &test
  adapter: postgresql
  host: localhost
  database: test_employees_manager
  pool: 5
  username: postgres
  encoding: utf8